#!/usr/bin/env bash

#Checking if no input argument is provided. If true program exits
if [[ $# -eq 0 ]]
then
    echo "ERROR: No input csv file provided" >&2
    exit 1
fi

#Checking if input file is present in current directory. If not found then program exits
if [[ ! -f "$1" ]]
then
    echo "ERROR: Input file not found in the current directory" >&2
    exit 1
fi

#Checking if input file is in csv format. If not then program exits
if [[ "$1" != *.csv ]]
then
    echo "ERROR: Input file expected in a csv format" >&2
    exit 1
fi

#Checking if input file is empty. If empty then program exits
if [[ ! -s "$1" ]]
then
    echo "ERROR: Empty file provided" >&2
    exit 1
fi

gawk -F ',' '
NR==1 {
    #initializing variables and contains other variables used but commented in this part.
    #max_occur_array - to be used for storing data on occurence count of video id
    n_row = 0
    total_views = 0
    #max_dislike_array - to be used for storing data on dislike count
    #max_engage_array - to be used for storing data on engagement rate
    #min_senti_array - to be used for storing data on net sentiment rate
    
}
NR==2 {
    #seting initial values for all variables based on 1st row of data
    max_occur_array[$1] = 1
    total_views += $3
    n_row = 1
    eng_rate = (($4 + $5) / $3)
    senti_rate = (($4 - $5) / $3)
    max_dislike_array["id"] = $1
    max_dislike_array["count"] = $5
    max_engage_array["id"] = $1
    max_engage_array["date"] = $2
    max_engage_array["value"] = eng_rate
    min_senti_array["id"] = $1
    min_senti_array["date"] = $2
    min_senti_array["value"] = senti_rate
    max_dislike_array["multi"] = 0
    max_engage_array["multi"] = 0
    min_senti_array["multi"] = 0
    
}
NR>2{
    #adding up views count for calculating mean
    total_views += $3
    n_row++

    likes = $4 + 0
    dislikes = $5 + 0
    views = $3 + 0

    #updating values of other variables if higher/lower(sentiment rate) value found
    #multi flag = 1 indicates multiple video ids with highest/lowest value for corresponding data point
    #multi flag = 0 indicates just 1 video id with highest/lowest value for corresponding data point
    #in case of multiple video ids for any data point, the required values(id and/or date) are stored as string separated by ##

    #updating data for occurence count
    if($1 in max_occur_array) {
        max_occur_array[$1] = max_occur_array[$1] + 1
    } else {
        max_occur_array[$1] = 1
    }

    #updating data for dislike count
    if(dislikes > max_dislike_array["count"] + 0) {
        max_dislike_array["id"] = $1
        max_dislike_array["count"] = $5
        max_dislike_array["multi"] = 0
    } else if(dislikes == max_dislike_array["count"] + 0){
        max_dislike_array["id"] = max_dislike_array["id"] "##" $1
        max_dislike_array["multi"] = 1
    }

    #Calculating engagement rate and sentiment rate for current row
    eng_rate = ((likes + dislikes) / views)
    senti_rate = ((likes - dislikes) / views)
    
    #updating engagement rate data
    if(eng_rate > max_engage_array["value"] + 0) {
        max_engage_array["id"] = $1
        max_engage_array["date"] = $2
        max_engage_array["value"] = eng_rate
        max_engage_array["multi"] = 0
    } else if(eng_rate == max_engage_array["value"] + 0) {
        max_engage_array["id"] = max_engage_array["id"] "##" $1
        max_engage_array["date"] = max_engage_array["date"] "##"$2
        max_engage_array["multi"] = 1
    }

    #updating sentiment rate data
    if(senti_rate < min_senti_array["value"] + 0) {
        min_senti_array["id"] = $1
        min_senti_array["date"] = $2
        min_senti_array["value"] = senti_rate
        min_senti_rate["multi"] = 0
    } else if(senti_rate == min_senti_array["value"] + 0) {
        min_senti_array["id"] = min_senti_array["id"] "##" $1
        min_senti_array["date"] = min_senti_array["date"] "##" $2
        min_senti_array["multi"] = 1
    }

    
}
END {
    #finding video id with max occurence
    most_freq_id = ""
    most_freq_count = 0
    most_freq_multi = 0
    for(id in max_occur_array) {
        id_count = max_occur_array[id] + 0
        
        if(id_count > most_freq_count) {
            most_freq_count = id_count
            most_freq_id = id
            most_freq_multi = 0
        } else if(id_count == most_freq_count) {
            most_freq_id = most_freq_id "##" id
            most_freq_multi = 1
        }
    }

    #printing max occurence data
    if(most_freq_multi == 0) {
        print "Most frequent video, ID: " most_freq_id
    } else if(most_freq_multi == 1) {
        size = split(most_freq_id, ids, /##/)
        print "Most frequent video, ID: " ids[1]
        for(i = 2; i <= size; i++) {
            print "ID: " ids[i]
        }
    }
    
    #printing mean views
    mean_views = (total_views / n_row)
    printf "Mean number of views: %.2f\n", mean_views

    #printing max dislike data
    if(max_dislike_array["multi"] + 0 == 0) {
        print "Max dislikes video, ID: " max_dislike_array["id"]
    } else if(max_dislike_array["multi"] + 0 == 1) {
        size = split(max_dislike_array["id"], ids, /##/)
        print "Max dislikes video, ID: " ids[1]
        for(i = 2; i <= size; i++) {
            print "ID: " ids[i]
        }
    }

    #printing max engagement rate data
    if(max_engage_array["multi"] + 0 == 0) {
        date = max_engage_array["date"]
        #date_f = substr(date, 7, 4) "-" substr(date, 4, 2) "-" substr(date, 1, 2)
        print "Highest engagement rate video, ID: " max_engage_array["id"] ", dated: " date
    } else if(max_engage_array["multi"] + 0 == 1) {
        size1 = split(max_engage_array["id"], ids, /##/)
        size2 = split(max_engage_array["date"], dates, /##/)
        print "Highest engagement rate video, ID: " ids[1] ", dated: " dates[1]
        for(i = 2; i <= size1 && i <= size2; i++) {
            print "ID: " ids[i] ", dated: " dates[i]
        }
    }

    #printing min sentiment rate data
    if(min_senti_array["multi"] + 0 == 0) {
        date = min_senti_array["date"]
        #date_f = substr(date, 7, 4) "-" substr(date, 4, 2) "-" substr(date, 1, 2)
        print "Least sentiment rate video, ID: " min_senti_array["id"] ", dated: " date
    } else if(min_senti_array["multi"] + 0 == 1) {
        size1 = split(min_senti_array["id"], ids, /##/)
        size2 = split(min_senti_array["date"], dates, /##/)
        print "Least sentiment rate video, ID: " ids[1] ", dated: " dates[1]
        for(i = 2; i <= size1 && i <= size2; i++) {
            print "ID: " ids[i] ", dated: " dates[i]
        }
    }
    exit 0
    #print "the end"
}
' "$1" 



